[project]
name = "ospo-data-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psycopg2>=2.9.10",
    "pyarrow>=18.0.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
